### ISSUE TITLE
AD review 02: minor level comments - part two

### ISSUE THREAD

**Issue by upros** [anima-wg/brski-cloud#147]
(6) p 10, sec 3.3.1. Redirect Response

The pledge MUST establish a provisional TLS connection with specified
local domain Registrar. The pledge MUST NOT use its Implicit Trust
Anchor database for validating the local domain Registrar identity.
The pledge MUST send a voucher request message via the local domain
Registrar.

It wasn't obvious to me why the pledge MUST NOT use it's implicit trust anchor database, and whether providing justification (or an explanation) would be helpful. Is this because it is just following the standard BRSKI flow from this point?

**Comment by mcr** [comment]
If it did use it's implicit trust anchor database, then it would probably fail.  Then what?

**Comment by upros** [comment]
I think this existing text is not quite right:

https://github.com/anima-wg/brski-cloud/blob/master/anima-brski-cloud.md#redirect-response-redirect-response

"The Cloud Registrar has returned a 307 response to a voucher request.

The pledge SHOULD restart its bootstrapping process using a new voucher request (with a fresh nonce) using the location provided in the HTTP redirect. Note the pledge can be redirected to a Registrar, in which case a provisional TLS connection will be necessary. The pledge might also be redirected to another Cloud Registrar, in which case the server certificate does need to be validated using its Implicit Trust Anchor database. Only when the certificate can be validated then additional additional 307 redirects MAY be accepted."

The pledge cannot tell the difference between a 307 to Owner Registrar vs. Cloud Registrar. It can maybe take a guess based on whether the Implicit Trust Anchor DB successfully verifies the next registrar or not.

This sentance is a problem "**The pledge might also be redirected to another Cloud Registrar, in which case the server certificate does need to be validated using its Implicit Trust Anchor database**"

So is the logic intended here more explicitly: 

If a pledge is 307ed to a Registrar, it MUST attempt to verify the registrar identity using its Implicit Trust Anchor DB. If the registrar identity cannot be verified by the Implicit Trust Anchor DB, then the pledge MUST NOT accept a subsequent 307 from that Registrar.

However, that means that if there is a "a chain of such VARs" the only way that will work is if their identites are all baked into the Implicit Trust Anchor DB, which I dont think is viable.

So.. I think if we want a chain of such VARs then we have to use provisional TLS for everything except the initial default Cloud Registrar connection.

**Comment by mcr** [comment]
> However, that means that if there is a "a chain of such VARs" the only way that will work is if their identites are all baked into the Implicit Trust Anchor DB, which I dont think is viable.

The implicit Trust Anchor DB can be a partial or full WebPKI.  In that case, it's just normal work.
It could also be some strategic subset, and/or VARs can be told that they must have a certificate one of the CAs in the trust anchor DB.  (And/or VARs could be provided with certificates from some subordinate CA that the OEM runs)
It's not like becoming a VAR for OEM FOO is something that randomly do.

**Comment by upros** [comment]
Can I be more explict here: 

Q1: Can the pledge use its Implicit TA for verifying the Owner Registrar identity? I think not.

Q2: The Pledge MUST do Provisional TLS against the Owner Registrar and only verify once its got the voucher. I think yes.

Q3: Can the pledge tell the difference between a 307 to Owner Registrar vs. Cloud Registrar? I think not.

Q4: The above all means that the pledge must do full TLS using its Implicit TA only for the initial default Cloud Registrar. And if its every 307ed, then its provisional TLS only. I think yets.

So, it doesnt really matter if a VAR Cloud Registrar (as opposed to the initial default cloud registrar) has an identity cert /partial PKI baked into the Implicit TA, cos how does the pledge know to treat any downstream 307ed registrar different from the Owner Registrar?

**Comment by upros** [comment]
Maybe the crux is: If pledge is 307ed - if it can verify downstream  registrar with implicit TA DB, then it may accept subsequent 307. 
If implicit TA DB verification fails, then it must establish provisional tls and MUST NOT follow another 307. Raised a PR.

**Comment by upros** [comment]
Cos the only way to verify a provisional is if pledge gets issued voucher, and if pledge is issued voucher - then it hasn't been 307ed.

Maybe a sentence about the pledge must not accept a 307 from an unverified registrar domain. And the only way to verify is by getting a voucher (hence no 307).

But a deployment question for you @mcr  : could a downstream cloud registrar VAR1 want to redirect  to yet another VAR2,even though the trust anchor to verify VAR1 is not in the implicit TA DB?

**Comment by mcr** [comment]
> But a deployment question for you @mcr : could a downstream cloud registrar VAR1 want to redirect to yet another VAR2,even though the trust anchor to verify VAR1 is not in the implicit TA DB?

I think that if the VARs are not in the implicit TA DB, then it's an operational failure.
In that case, the pledge should post telemetry saying so to the initial cloud registrar.

**Comment by upros** [comment]
Excellent, thats excatly what this PR clarifies: https://github.com/anima-wg/brski-cloud/pull/148/files
