### ISSUE TITLE
Brian Carpenter - Interested Parties

### ISSUE THREAD

**Issue by upros** [anima-wg/brski-cloud#15]
>  2.1. Interested Parties

I find this section too telegraphic. Needs a bit more grammar...

**Comment by upros** [comment]
Maybe we just delete this section completely @mcr ?

**Comment by mcr** [comment]
I think we should eliminate the heading, but expand the content to better match the diagram.

**Comment by upros** [comment]
I'm not convinced.

In the rest of the doc, we never mention OEM or Network integrator.

And Network operator is only mentioned again in secetion "Issues with Security of HTTP Redirect"

I lean to delete completely, unless you have some explicit ideas and concepts you need to get across. FIne if you do - maybe include that in your abstract rewrite PR?
