### ISSUE TITLE
Brian Carpenter - Network Connectivity

### ISSUE THREAD

**Issue by upros** [anima-wg/brski-cloud#16]
>  2.2. Network Connectivity
> 
> The assumption is that the pledge already has network connectivity 
> prior to connecting to the cloud registrar. The pledge must have an IP 
> address,

Should specify that you mean "routeable" IP address, I think. (I suppose it could be a ULA in some deployments?)

**Comment by mcr** [comment]
I'm not sure routeable is correct. I think that many will think it means an address which is world reachable, when any kind of NAT44, SOCKS, or HTTP-PROXY'able address would work.
(there are still enterprises that use 10./8 without a default route and socks/http-proxy...)
