### ISSUE TITLE
Esko Dijk - YANG issues

### ISSUE THREAD

**Issue by upros** [anima-wg/brski-cloud#22]
- the YANG contains "RFC XXXX: Voucher Profile for Cloud redirected Devices" - it seems the name needs updating and there should be an RFC ednote here saying the reference is "this RFC". Correct?

- YANG contains this:
     description "Base the constrained voucher upon the regular one"; This looks like a copy/paste leftover from constrained-voucher; correct that it should be modified? (Would this also bump the YANG version and date then?)

- YANG description for leaf "est-domain" does not explicitly say the word "EST server" which I think it should. So this URI directs to the EST server in the owner's domain.

- could YANG support the use case of combining the voucher-constrained  format (that extends base voucher) and the voucher-redirected format (from current draft) ?  Would that require yet another new YANG module?

**Comment by mcr** [comment]
Also, the YANG extensions need to move to RFC8366bis!
https://github.com/anima-wg/voucher/issues/23
