### ISSUE TITLE
Definition of "EST registrar" or rename to "EST server"

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/brski-cloud#32]
(WGLC review comment 2022-11-21 , [link](https://mailarchive.ietf.org/arch/msg/anima/GmqzbIElsIGW2HPMnfwzWD5blFI/))

- what is the "EST Registrar"? It is not defined so far. Wouldn't it be better to use RFC 8995 terminology of "EST server" ?   So if the cloud Registrar supplies the Voucher and that redirects to an owner's EST server, we can call that "EST server" or "owner EST server".  It's not a Registrar necessarily, so better not use "EST Registrar" or "owner Registrar".    The latter term "owner Registrar" is already used for something else: the server that provides a voucher to the pledge.

Interesting to consider that the owner's EST server *could* be on the same host as a BRSKI Registrar i.e. handing out vouchers to Pledges, even if the cloud-Registrar-supporting Pledge already got its voucher from the cloud-Registrar.  But let's not say such things in the document to avoid complicating it.

**Comment by mcr** [comment]
sentence removed in work in February.

**Comment by EskoDijk** [comment]
@mcr There's one more remaining instance of "EST registrar" in 7.4:

> Owner's EST [RFC7030] Registrar,

could use regular "owner registrar" here.
(I wanted to reopen this issue now but I can't)

**Comment by mcr** [comment]
fixed in 115c335.
