### ISSUE TITLE
YANG contains "RFC XXXX" and an old name of present draft; add ednote for RFC editor

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/brski-cloud#33]
(WGLC review comment 2022-11-21 , [link](https://mailarchive.ietf.org/arch/msg/anima/GmqzbIElsIGW2HPMnfwzWD5blFI/))

- the YANG contains "RFC XXXX: Voucher Profile for Cloud redirected Devices" - it seems the name needs updating to the latest draft name and there should be an RFC editor ednote here saying the reference is "this RFC". Correct?

**Comment by mcr** [comment]
closed 033ac814a6784b66ff361419d0093a927e585080
