### ISSUE TITLE
Abstract is too short

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/brski-cloud#37]
(WGLC review comment Brian 2022-11-20 [link](https://mailarchive.ietf.org/arch/msg/anima/5C-2A41kNNgdnjbdYu1-P6dKSQo/))

> Abstract

This is a bit short. I think it should provide a little context for a casual reader (what is BRSKI, what is a pledge, what is a registrar).

**Comment by mcr** [comment]
closed by 6a8e3814dc850e2eea5aebca0e89c3e29f2e0ca6
