### ISSUE TITLE
Toreless - draft-5 section 1.2:  core argument concerns

### ISSUE THREAD

**Issue by mcr** [anima-wg/brski-cloud#53]
````
154	   might be preloaded with a configuration that changes the Cloud
155	   Registrar URL to point to a VAR.  Such an effort would require
156	   unboxing each device in a controlled environment, but the
157	   provisioning could occur using a regular BRSKI or SZTP [RFC8572]
158	   process.

I think VAR is an unnecessary term and the whole paragraph is somewhat confusing.

If i understand it correctly, the core argument is like this:

The procedures specified in this document are an alternative to mechanisms
possible with just BRSKI to reduce operational cost.

Consider pledges are to be enrolled when being connected solely to the
Internet, but no owner based network. Likewise, the Registar is assumed to be
only connected to the Internet. The challenge in this case is for the pledge to
discover a URI for the Oners Registar. In the absence of the procdures described
in this doument, BRSKI could be used, but the pledge would need to be
pre-staged with that URI. In one instance, the seller of the pledge could
attach to the shipment of the pledge a USB stick pre-populated with a file
containing that Owner Registar URI, and that USB stick would need to be
inserted into the pledge to enavble enrolment. This is but one option,
and compared to similar alternatives, it does not require unpacking/configuration/repackaging
of the pledge at the sellers site, but only configuration of a USB stick

Yada yada... i really don't know how to make this shorter without looking readers
who do not live & breathe this stuff, so it probably is all better suited to be
put later into the document and only put a pointer to such a chapter here into the
Introduction.
````

**Comment by upros** [comment]
@mcr  @toerless  a question on this. Lets say a VAR/systems integrator/whatever has change configured via whatever mechanisms (USB, unboxing the box, etc.) a new registrar URI.

Does this override the default manufacturer URI? i.e. does the device now think that the VAR/SI provisioned URI is default Cloud Registrar URI??

Or does the device now think this is a local domain registrar i.e. the config update/USB/whatever is really an alternative to https://datatracker.ietf.org/doc/html/rfc8995#section-4.1 and https://datatracker.ietf.org/doc/html/rfc8995#section-appendix.b ? The logical conclusion being, if the pledge attempts to connect to that VAR-provisioned registrar URI and fails, does it then fallback to the default cloud registrar URI?

The answer will be device-specific. Some devices/OEMs may allow the VAR to overwrite the default Cloud Registrar URI. Some devices/OEMs will not but will allow provisoin of an operator-specific registrar URI.

Should we mention this in this context?
