### ISSUE TITLE
explain why voucher pinning is relevant

### ISSUE THREAD

**Issue by mcr** [anima-wg/brski-cloud#57]
219	   TWO CHOICES: 1.  Cloud Registrar redirects to Owner Registrar 2.
220	   Cloud Registrar returns VOUCHER pinning Owner Register.

This paragraph comes totall unexpected without context. Pinning is unexplained.
Maybe less ternse explanation here.

**Comment by upros** [comment]
@mcr  this one has already been address in a previous PR. Suggest we close as addressed? Struggling to find the exact PR where this was removed.
