### ISSUE TITLE
Toreless - remove OEM term

### ISSUE THREAD

**Issue by mcr** [anima-wg/brski-cloud#59]
246	   1.  OEM - Equipment manufacturer.  Operate the MASA.

The rest of the document does not use the term OEM. Delete

**Comment by toerless** [comment]
It happens only twice in the document and provides no explanation why the
term OEM is useful. In RFC8995, the term "manufacturer" includes the option OEM,
but it also does not elaborate what this means. Eg: if my car or train from ManufacturerA 
comes with an embedded compute unit from a compute unit (pledge) from 
OemB. Is there any repsonsibility of A if B runs the cloud registrar or even
MASA ? 

Aka: There is no good reference for the difference between BRSKI and OEM
or VAR mean to requirements of implementation, additional API etc. pp.
"BRSKI operational considerations" draft ? 

If you really are fixated, then say (...or OEM/VAR as defined in RFC8995 as
alternatives for manufacturer).

Cheers
    Toerless
