### ISSUE TITLE
improve or remove Network operator, Network Integrator

### ISSUE THREAD

**Issue by mcr** [anima-wg/brski-cloud#60]
248	   2.  Network operator.  Operate the Owner Registrar.  Often operated
249	       by end owner (company), or by outsourced IT entity.

This is only used twice below and the second time its not clear its the same
operator.

251	   3.  Network integrator.  They operate a Cloud Registrar.

You never use the term Network integrator in the rest of the document. Delete

Aka: This whole section doesn't make sense unless you add some more explanation
(but likely it can just go).

**Comment by upros** [comment]
This section is already removed from the latest draft-08. Cant we just close this issue @mcr  ?
