### ISSUE TITLE
Toreless - draft-5 section 4.2: validation vs authentication of EST server

### ISSUE THREAD

**Issue by mcr** [anima-wg/brski-cloud#80]
```
568	   validated using the pinned-domain-cert value provided in the voucher
569	   as described in [BRSKI] section 5.6.2.  This involves treating the
570	   artifact provided in the pinned-domain-cert as a trust anchor, and
571	   attempting to validate the EST Registrar from this anchor only.

s/validate/authenticate/
```

**Comment by mcr** [comment]
RFC6125 speaks about validating of identity.
RFC9525 now speaks about verifying as well, neither speak about authentication.
Propose not to change, @toerless

**Comment by upros** [comment]
Well I guess the two terms are linked.  A client authenticates a server's identity by validating (or verifying) the server's certificate @mcr @toerless
